# Generated by Django 5.0 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Process name', max_length=50)),
                ('code', models.CharField(help_text='Unique process code (used as filename)', max_length=100, unique=True)),
                ('script', models.TextField(help_text='Python script content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['code'],
            },
        ),
    ]
