# Generated by Django 5.0 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source of the webhook (e.g., 'slack', 'stripe', 'github')", max_length=100)),
                ('payload', models.JSONField(help_text='The webhook payload data')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the webhook was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the webhook was processed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
    ]
